<?php

class m170116_102550_create_elgpmkst extends CDbMigration
{
	public function safeUp()
	{
		$sql = <<<SQL
CREATE TABLE ELGPMKST (
    ELGPMKST1  INTE PRIMARY KEY,/* INTE = INTEGER DEFAULT 0 NOT NULL */
    ELGPMKST2  INTE /* INTE = INTEGER DEFAULT 0 NOT NULL */,
    ELGPMKST3  INTE /* INTE = INTEGER DEFAULT 0 NOT NULL */,
    ELGPMKST4  INTE /* SMAL = SMALLINT DEFAULT 0 NOT NULL */,
    ELGPMKST5  DOUB /* DOUB = DOUBLE PRECISION DEFAULT 0 NOT NULL */
);

SQL;
		$this->execute($sql);

		$sql = <<<SQL
ALTER TABLE ELGPMKST ADD CONSTRAINT FK_ELGPMKST_1 FOREIGN KEY (ELGPMKST2) REFERENCES ELG (ELG1) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_ELGPMKST_2 FOREIGN KEY (ELGPMKST3) REFERENCES ST (ST1) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_ELGPMKST_4 FOREIGN KEY (ELGPMKST4) REFERENCES vmpv (vmpv1) ON DELETE CASCADE ON UPDATE CASCADE;

SQL;
		$this->execute($sql);
	}

	public function safeDown()
	{
		//echo "m170116_102550_create_elgpmkst does not support migration down.\\n";
		//return false;
		$sql = <<<SQL
		DROP TABLE ELGPMKST;
SQL;
		$this->execute($sql);
	}
}